idf_component_register(
  SRCS
  "src/Display.cpp"
  "src/I2cBus.cpp"
  "src/I2sBus.cpp"
  "src/GpioInput.cpp"
  "src/WifiClient.cpp"
  "src/HttpClient.cpp"
  "src/Mp3Decoder.cpp"
  "lib/minimp3/minimp3_impl.c"
  INCLUDE_DIRS
  "include"
  "lib/minimp3"
  REQUIRES
  common
  driver
  log
  freertos
  esp_http_client
  esp_wifi
  nvs_flash
  PRIV_REQUIRES
  mbedtls)
