idf_component_register(
  SRCS
  "src/AdcReader.cpp"
  "src/Display.cpp"
  "src/I2cBus.cpp"
  "src/I2sBus.cpp"
  "src/GpioInput.cpp"
  "src/WifiClient.cpp"
  "src/HttpClient.cpp"
  "src/Mp3Decoder.cpp"
  "src/PersistentStorage.cpp"
  "src/ProvisioningPortal.cpp"
  "src/FileSystem.cpp"
  "lib/minimp3/minimp3_impl.c"
  INCLUDE_DIRS
  "include"
  "lib/minimp3"
  REQUIRES
  common
  driver
  log
  freertos
  esp_adc
  esp_http_client
  esp_http_server
  esp_wifi
  esp_netif
  esp_event
  nvs_flash
  esp_driver_i2c
  esp_driver_i2s
  esp_driver_gpio
  PRIV_REQUIRES
  mbedtls
  littlefs)

littlefs_create_partition_image(storage ${CMAKE_SOURCE_DIR}/resources/json
                                FLASH_IN_PROJECT)
