@startuml seq_skip_station.puml
title ESP32 Internet Radio - Sequence Diagram (Skip Station)

actor "app_main" as APP
box "Core" #LightBlue
participant "EventTask\n(IEventQueue)" as CORETASK
participant "AppContext" as CTX
participant "AppController" as CTRL
end box

box "Commands" #LightCyan
participant "PlayStopSkipCommand" as CMD
end box

box "Services" #LightGreen
participant "PlayerService" as PLSVC
participant "StationRepository" as REPO
end box

box "Common" #LightGray
participant "TaskRunner" as TR
end box

box "Adapters" #LightYellow
participant "Display\n(IDisplay)" as DISP
participant "I2sBus\n(II2sBus)" as I2S
participant "WifiClient\n(IWifiClient)" as WC
participant "HTTPClient\n(IHTTPClient)" as HTTP
participant "MP3Decoder\n(IMP3Decoder)" as MP3D
end box


box "ESP-IDF" #LightGray
participant "ESP-IDF" as IDF
end box

== Init ==
activate APP
APP -> CTX ++: AppContext.init()
CTX -> WC ++: init()
WC -> IDF ++: init wifi and start it
return res 
return res 

CTX -> I2S ++: init()
I2S -> IDF ++: i2s_new_channel()  
return res
I2S -> IDF ++: i2s_channel_init_std_mode()
return res
I2S -> IDF ++: i2s_channel_enable()
return res
return res

CTX -> REPO ++: init()
return res
CTX -> PLSVC ++: init()
return res
CTX -> CORETASK ++: init()
return res
CTX -> CTRL ++: init()
return res
deactivate CTX

== Skip (Next/Prev) ==
CORETASK  -> CTRL ++: onEvent(ButtonPressedEvent{.button=Next (or Previous)})
note left
see details in seq_press_button.puml
end note
CTRL -> CMD ++: create
CTRL -> CMD : handle(event)
CMD -> PLSVC ++: get current status
return status

alt button == Next
    CMD -> REPO ++: nextStation
    return stationData
else button == Previous
    CMD -> REPO ++: prevStation
    return stationData
end

alt status == Playing || status == Buffering
    CMD -> PLSVC: stop()
    note right
    see details in seq_stop_station.puml
    end note
end

CMD -> PLSVC: playStation(stationData.url)
note right
see details in seq_play_station.puml
end note


@enduml
    